### PR TITLE
Expose how user is active

### PR DESCRIPTION
**Pull request by kwbock**
Adds method to determine if user has been explicitly activated, as
opposed to via a percentage or group

### CODE REVIEW

**Comment by jacortinas** [comment]
This looks like a useful addition, @reneklacan what do you think?

**Comment by reneklacan** [comment]
Agree, 👍 ... Thank you!

**Comment by reneklacan** [comment]
rollout 2.2.4 including this change has been released

**Comment by JohnBaku** [comment]
@reneklacan thanks!

**Pull request merged**
