### PR TITLE
Added feature delete function

### PR DESCRIPTION
**Pull request by ainsleyc**
Noticed that there wasn't a function to delete existing feature keys, added one plus a couple tests.

Let me know if there are any issues. Thanks!

### CODE REVIEW

**Comment by mcasper** [comment]
@EricR Any word on this? This feature would be very useful for my use case!

**Comment by carlthuringer** [comment]
:+1:

**Comment by elopez-pt** [comment]
Would be nice to have this small feature

**Comment by reneklacan** [comment]
Thank you!

**Pull request merged**
