### PR TITLE
Allow percentage to be float with three decimal points

### PR DESCRIPTION
**Pull request by reneklacan**
* add support for float percentages, eg: `$rollout.activate_percentage(:chat, 0.001)`

### CODE REVIEW

**Comment by jacortinas** [comment]
:+1:

**Comment by JohnBaku** [comment]
@reneklacan I would only allow up to two decimal points. If their is a need for more in the future I would add it then... three is a big much! Yes, I am being serious! :-p

**Comment by JohnBaku** [comment]
FYI... this fixes: https://github.com/fetlife/fetlife-web/issues/4286

**Comment by rakvat** [comment]
:+1:

**Comment by rakvat** [comment]
@JohnBaku I would have needed that when rolling out event_logging for interana :+1: for 3 decimal points

**Comment by reneklacan** [comment]
@JohnBaku you can still use 2 decimal points ... it's not just for FL and 3 decimal point feel like good balanced compromise

**Comment by JohnBaku** [comment]
@ReadmeCritic balance compromise between what and what LOL? :-p Has someone asked for more? :-p

Oh... okay... I just saw @rakvat's comment... okay.. if their is a need... then that is cool!

**Pull request merged**
