### PR TITLE
Add support for split tests with random distributions

### PR DESCRIPTION
**Pull request by kmendes**

### CODE REVIEW

**Comment by thedrow** [comment]
@kmendes FYI This PR needs to be rebased

**Comment by nj** [comment]
@kmendes Did you ever see the message by @thedrow?

You need to handle the merge-conflict, so currently the PR is just stuck.

**Comment by thedrow** [comment]
Was this resolved or simply rejected?

**Comment by nj** [comment]
@thedrow Agree, 3 years and no words seems odd

**Comment by reneklacan** [comment]
@thedrow @nj I'm sorry for not being clear. Rejected for now. PR was never rebased and others didn't show enough support for this feature.

But if you feel confident that this feature would add a lot of value and any of you rebases these changes and creates a new PR for them, I'd be happy to merge it.

**Pull request closed without merging**
