### PR TITLE
Remove RubyForge project from gemspec

### PR DESCRIPTION
**Pull request by maclover7**

### CODE REVIEW

**Comment by EricR** [comment]
I would merge this in if I still had maintainer status for this repo.

@JohnBaku I'd be willing to continue maintaining this if nobody else at FetLife wants to atm.

**Comment by JohnBaku** [comment]
@ericr thanks... we will discuss this and see what peeps say. cc/ @lauradoox

**Comment by lauradoox** [comment]
ack

**Comment by pboling** [comment]
@JohnBaku Is this gem maintained?  I'm considering using it.

**Comment by JohnBaku** [comment]
@pboling maintained is a very strong word! :-/

All jokes aside... I would say currently.. it's not being actively maintained.

**Comment by JohnBaku** [comment]
@EricR since you approved this... I will merge it!

**Pull request merged**
